### PR TITLE
its onchain, not on-chain

### PR DESCRIPTION
**Pull request by olegakbarov**
Like it is not e-mail and not on-line :)

PS 

Awesome job overall 👍

### CODE REVIEW

**Comment by fiveoutofnine** [comment]
Never understood the `e-mail:email::on-chain:onchain` or `on-line:online::on-chain:onchain` allusion. I understand the motive of using "onchain" is something like signifying a new paradigm of sorts, but what has that got to do with the 2 analogies? IMO, the better choice is the one that is more widely used and communicates more clearly. ATM, I think it's with the hyphen.

**Comment by fiveoutofnine** [comment]
(sorry, this is my personal site, so I'm also going to be opinionated in response ha)

**Comment by olegakbarov** [comment]
This is not over.

**Comment by fiveoutofnine** [comment]
hehehe

**Pull request closed without merging**
