### PR TITLE
Development

### PR DESCRIPTION
**Pull request by kmiguel10**

### CODE REVIEW

**Comment by fiveoutofnine** [comment]
heh, accident?

**Comment by kmiguel10** [comment]
This is so embarrassing I’m so sorry…Sent from my iPhoneOn Jan 11, 2024, at 6:52 AM, fiveoutofnine ***@***.***> wrote:﻿
heh, accident?

**Comment by fiveoutofnine** [comment]
hahaha no worries at all :) glad you are taking inspo/bits from my site; as a fyi I will be doing a big update soon (next 14+app router, _many\_ new components, couple new pages, etc.)

**Comment by kmiguel10** [comment]
That’s awesome! I actually did a nextjs13 version initially but I couldn’t get this one thing working so I gave up and straight up forked your repo … I’m looking forward to it. Won’t be sending embarrassing PRs for that one 🫢.Sent from my iPhoneOn Jan 11, 2024, at 7:28 AM, fiveoutofnine ***@***.***> wrote:﻿
hahaha no worries at all :) glad you are taking inspo/bits from my site; as a fyi I will be doing a big update soon (next 14+app router, _many_ new components, couple new pages, etc.)

**Pull request closed without merging**
